config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # USER
  resources :work_orders, only: [:index, :show, :edit, :update]

  # ADMIN
  # namespace
  # after_create in user to create manager
  namespace :manager do
    resources :work_orders
    resources :team_leaders
    resources :dashboard, only: :index
  end

end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user
  has_many :team_leaders
end

app/models/team_leader.rb
class TeamLeader < ApplicationRecord
  belongs_to :user
  belongs_to :manager
  has_many :work_orders

  def get_team_name
    "#{team_name}"
  end

end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < ApplicationController


  def index
    # WORK ORDERS - Filtros + Show all for index
    @work_orders_full = WorkOrder.all
    @work_orders = @work_orders_full

    @work_orders = WorkOrder.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    @work_orders =  @work_orders.where(team_leader_id: params[:team]) if params[:team].present?
    @work_orders =  @work_orders.where(priority: params[:priority]) if params[:priority].present?
    @work_orders =  @work_orders.where(status: params[:status]) if params[:status].present?
    # @work_orders =  @work_orders.where(due_date: params[:due_date]) if params[:due_date].present?

    # WORK ORDERS - Calendario
    @events = WorkOrder.where.not(due_date: nil).map { |w| { title: w.name, start: w.due_date } }

    # TEAM - Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end

    # # MAP
    @work_orders_full = WorkOrder.geocoded
    @markers = @work_orders_full.map do |order|
      if order.status == 1
        {
          lat: order.latitude,
          lng: order.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { order: order }),
          image_url: helpers.asset_url('icon-3-c_160.png') #amarelo
        }
      elsif order.status == 2
        {
          lat: order.latitude,
          lng: order.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { order: order }),
          image_url: helpers.asset_url('icon-4-c_160.png') #azul
        }
      else
        {
          lat: order.latitude,
          lng: order.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { order: order }),
          image_url: helpers.asset_url('icon-2-b_160.png') #verde
        }
      end
    end

    @chart = WorkOrder.group(:status).count
    @chart.keys.each do |key|
      @chart[['Aberto', 'Em andamento', 'Concluído'][key - 1]] = @chart.delete key
    end
  end
end

app/controllers/manager/team_leaders_controller.rb
class Manager::TeamLeadersController < ApplicationController
  before_action :set_team_leader, only: %i[show edit update delete]

  def index
    # Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end
  end

  def new
    # Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end

    # New
    @team_leader = TeamLeader.new
  end

  def create
    # passar ID do manager?
    # mostrar lista de usuários para selecionar um e atribuir ao Team.
    # Não está salvando novo TEAM

    @team_leader = TeamLeader.new(team_leader_params)
    @team_leader.manager = current_user.manager
    if @team_leader.save
      redirect_to manager_team_leaders_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    # Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end
  end

  def update
    @team_leader.update(team_leader_params)
    redirect_to manager_team_leaders_path
  end

  def destroy
    @team_leader.destroy
    redirect_to team_leaders_path
  end

  private

  def set_team_leader
    @team_leader = TeamLeader.find(params[:id])
  end

  def team_leader_params
    params.require(:team_leader).permit(:team_name, :user_id, :manager_id)
  end
end

app/controllers/manager/work_orders_controller.rb
class Manager::WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[show edit update destroy]

  def index
    @team_leaders = TeamLeader.all
    @work_orders_full = WorkOrder.all
    @work_orders = @work_orders_full

    @work_orders = WorkOrder.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    @work_orders = @work_orders.where(team_leader_id: params[:team]) if params[:team].present?
    @work_orders = @work_orders.where(priority: params[:priority]) if params[:priority].present?
    @work_orders = @work_orders.where(status: params[:status]) if params[:status].present?
    @work_orders = @work_orders.where(due_date: params[:due_date]) if params[:due_date].present?

    @events = WorkOrder.where.not(due_date: nil).map { |w| { title: w.name, start: w.due_date } }
  end

  def new
    @work_order = WorkOrder.new
  end

  def show
    @marker = {
      lat: @work_order.latitude,
      lng: @work_order.longitude,
      image_url: helpers.asset_url('shovel_marcador.png'),
      infoWindow: render_to_string(partial: "info_window", locals: { work_order: @work_order })
    }


    # @work_order.tasks.pluck(:done)
    # @chart = WorkOrder.group(:done).count
    # @chart.keys.each do |key|
    #   @chart[['Aberto', 'Em andamento', 'Concluído'][key - 1]] = @chart.delete key
    # end
  end

  def create
    @work_order = WorkOrder.new(work_order_params)
    # raise
    if @work_order.save
      redirect_to manager_dashboard_index_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @work_order.update(work_order_params)
    redirect_to manager_work_orders_path
  end

  def destroy
    @work_order.destroy
    redirect_to manager_dashboard_index_path
  end

  private

  def set_work_order
    @work_order = WorkOrder.find(params[:id])
  end

  def work_order_params
    params.require(:work_order).permit( :name,
                                        :priority,
                                        :address,
                                        :due_time,
                                        :due_date,
                                        :description,
                                        :completion_date,
                                        :start_photo,
                                        :end_photo,
                                        :team_leader_id,
                                        :status,
                                        :report,
                                        tasks_attributes: [:id, :description, :done, :_destroy])

  end

end

app/views/manager/team_leaders/_form.html.erb
<%= simple_form_for @team_leader, url: manager_team_leaders_path do |f| %>
  <%= f.input :team_name %>
  <%= f.association :user %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>


<%#= f.association :user, collection: User.where(admin: false) %>

app/views/manager/team_leaders/_sidebar.html.erb
<!-- Sidebar -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3> <br>MENU<br> </h3>
    </div>

    <ul class="list-unstyled components">
        <p></p>
        <li class="active">

            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Manager</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                <%= link_to "Dashboard", manager_dashboard_index_path%>
                </li>
                <li>
                <%= link_to "Ordens de Serviço", manager_work_orders_path%>
                </li>
                <li>
                <%= link_to "Equipes", manager_team_leaders_path%>
                </li>
            </ul>
        </li>
        <br>
        <br>
        <br>
        <li>
        <%= link_to "Sair", destroy_user_session_path, method: :delete %>
        </li>
    </ul>
</nav>

app/views/manager/team_leaders/edit.html.erb
<div class="wrapper">
  <div id="content">
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
      <button type="button" id="sidebarCollapse" class="btn btn-info">
      <i class="fas fa-align-left"></i>
      <span></span>
      </button>
  <!-- </nav> -->
  <%= render 'sidebar' %>
  </div>


  <div class="container-full content-master d-flex align-items-center">
    <div class="row">
        <h4>Team / Edit</h4>
      <div class="col-12">
        <h3>Edit Team</h3>
        <%= simple_form_for @team_leader, url: manager_team_leader_path do |f| %>
          <%= f.input :team_name %>
          <%= f.association :user %>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
        <%= link_to 'Cancelar', manager_team_leaders_path %>
      </div>
    </div>
  </div>
</div>

app/views/manager/team_leaders/index.html.erb
<div class="conteiner">   <!-- Igual ao d-flex -->

  <div id="content">
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
      <button type="button" id="sidebarCollapse" class="btn btn-info">
      <i class="fas fa-align-left"></i>
      <span></span>
      </button>
  <!-- </nav> -->
  <%= render 'sidebar' %>
  </div>

  <div class="container-full content-master">
    <div class="row">
      <div class="col-8 offset-2">
      <!-- Inicio da 1º coluna -->

      <div>
              <div class="card-dashboard-header">
              <p class="d-flex justify-content-center">
              <%= link_to "Criar novo time", new_manager_team_leader_path, class: "btn btn-primary my-2" %></p>
              </div>

                <!-- Filtros Work Orders -->
      <div class="card m-2">
      <div class="card-header d-flex justify-content-center" style="font-size: 12px;">Teams-index</div>
      <div class="card-body">
              <%= form_tag manager_team_leaders_path, method: :get do %>
              <div class="search-form-control form-group">
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control string required",
                  placeholder: "Find a team" %>
                <%= submit_tag "Search", class: "btn btn-secondary" %>
                <% end %>
              </div>

              <%= link_to "Limpar", manager_team_leaders_path, class: "btn btn-flat" %>

                  <!-- Work Orders index -->
                  <div class="card my-3 text-center" style="font-size: 11px; padding: 5px" >
                   <table class="table table-borderless table-hover table-sm">
                      <thead class="thead-light">
                        <tr>
                        <th scope="col">Team Name</th>
                        </tr>
                      <tbody>
                        <% @team_leaders.each do |manager_team_leader| %>
                        <tr>
                          <th scope="row"><%= link_to manager_team_leader.team_name, edit_manager_team_leader_path(manager_team_leader) %> </th>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
          </div>
          </div>
        </div>

      <!-- Final da 1º coluna -->
      </div>
</div>
</div>
</div>
</div>

app/views/manager/team_leaders/new.html.erb
<div class="wrapper">
  <div id="content">
    <button type="button" id="sidebarCollapse" class="btn btn-info">
    <i class="fas fa-align-left"></i>
    <span></span>
    </button>
  <%= render 'sidebar' %>
  </div>
  <div class="container-full content-master">
    <div class="row">
      <h4>Team / New</h4>
      <div class="col-12">
        <h3>Create New Team</h3>
        <%= render 'form' %>
        <%= link_to 'Cancelar', manager_team_leaders_path %>
      </div>
    </div>
  </div>
</div>