config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # USER
  resources :work_orders, only: [:index, :show, :edit, :update]

  # ADMIN
  # namespace
  # after_create in user to create manager
  namespace :manager do
    resources :work_orders
    resources :team_leaders
    resources :dashboard, only: :index
  end

end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :user
  has_many :team_leaders
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  # enum status: { Aberta: 0, 'Em andamento': 1, Concluido: 2 }
  has_many :tasks, inverse_of: :work_order, dependent: :destroy
  belongs_to :team_leader

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  geocoded_by :address
  validates :name, uniqueness: true
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :start_photo, PhotoUploader
  mount_uploader :end_photo, PhotoUploader
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < ApplicationController


  def index
    # WORK ORDERS - Filtros + Show all for index
    @work_orders_full = WorkOrder.all
    @work_orders = @work_orders_full

    @work_orders = WorkOrder.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    @work_orders =  @work_orders.where(team_leader_id: params[:team]) if params[:team].present?
    @work_orders =  @work_orders.where(priority: params[:priority]) if params[:priority].present?
    @work_orders =  @work_orders.where(status: params[:status]) if params[:status].present?
    # @work_orders =  @work_orders.where(due_date: params[:due_date]) if params[:due_date].present?

    # WORK ORDERS - Calendario
    @events = WorkOrder.where.not(due_date: nil).map { |w| { title: w.name, start: w.due_date } }

    # TEAM - Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end

    # # MAP
    @work_orders_full = WorkOrder.geocoded
    @markers = @work_orders_full.map do |order|
      if order.status == 1
        {
          lat: order.latitude,
          lng: order.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { order: order }),
          image_url: helpers.asset_url('icon-3-c_160.png') #amarelo
        }
      elsif order.status == 2
        {
          lat: order.latitude,
          lng: order.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { order: order }),
          image_url: helpers.asset_url('icon-4-c_160.png') #azul
        }
      else
        {
          lat: order.latitude,
          lng: order.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { order: order }),
          image_url: helpers.asset_url('icon-2-b_160.png') #verde
        }
      end
    end

    @chart = WorkOrder.group(:status).count
    @chart.keys.each do |key|
      @chart[['Aberto', 'Em andamento', 'Concluído'][key - 1]] = @chart.delete key
    end
  end
end

app/controllers/manager/team_leaders_controller.rb
class Manager::TeamLeadersController < ApplicationController
  before_action :set_team_leader, only: %i[show edit update delete]

  def index
    # Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end
  end

  def new
    # Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end

    # New
    @team_leader = TeamLeader.new
  end

  def create
    # passar ID do manager?
    # mostrar lista de usuários para selecionar um e atribuir ao Team.
    # Não está salvando novo TEAM

    @team_leader = TeamLeader.new(team_leader_params)
    @team_leader.manager = current_user.manager
    if @team_leader.save
      redirect_to manager_team_leaders_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    # Filtros + Show all for index
    if params[:query].present?
      @team_leaders = TeamLeader.where("team_name ILIKE ?", "%#{params[:query]}%")
    else
      @team_leaders = TeamLeader.all
    end
  end

  def update
    @team_leader.update(team_leader_params)
    redirect_to manager_team_leaders_path
  end

  def destroy
    @team_leader.destroy
    redirect_to team_leaders_path
  end

  private

  def set_team_leader
    @team_leader = TeamLeader.find(params[:id])
  end

  def team_leader_params
    params.require(:team_leader).permit(:team_name, :user_id, :manager_id)
  end
end

app/controllers/manager/work_orders_controller.rb
class Manager::WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[show edit update destroy]

  def index
    @team_leaders = TeamLeader.all
    @work_orders_full = WorkOrder.all
    @work_orders = @work_orders_full

    @work_orders = WorkOrder.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    @work_orders = @work_orders.where(team_leader_id: params[:team]) if params[:team].present?
    @work_orders = @work_orders.where(priority: params[:priority]) if params[:priority].present?
    @work_orders = @work_orders.where(status: params[:status]) if params[:status].present?
    @work_orders = @work_orders.where(due_date: params[:due_date]) if params[:due_date].present?

    @events = WorkOrder.where.not(due_date: nil).map { |w| { title: w.name, start: w.due_date } }
  end

  def new
    @work_order = WorkOrder.new
  end

  def show
    @marker = {
      lat: @work_order.latitude,
      lng: @work_order.longitude,
      image_url: helpers.asset_url('shovel_marcador.png'),
      infoWindow: render_to_string(partial: "info_window", locals: { work_order: @work_order })
    }


    # @work_order.tasks.pluck(:done)
    # @chart = WorkOrder.group(:done).count
    # @chart.keys.each do |key|
    #   @chart[['Aberto', 'Em andamento', 'Concluído'][key - 1]] = @chart.delete key
    # end
  end

  def create
    @work_order = WorkOrder.new(work_order_params)
    # raise
    if @work_order.save
      redirect_to manager_dashboard_index_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @work_order.update(work_order_params)
    redirect_to manager_work_orders_path
  end

  def destroy
    @work_order.destroy
    redirect_to manager_dashboard_index_path
  end

  private

  def set_work_order
    @work_order = WorkOrder.find(params[:id])
  end

  def work_order_params
    params.require(:work_order).permit( :name,
                                        :priority,
                                        :address,
                                        :due_time,
                                        :due_date,
                                        :description,
                                        :completion_date,
                                        :start_photo,
                                        :end_photo,
                                        :team_leader_id,
                                        :status,
                                        :report,
                                        tasks_attributes: [:id, :description, :done, :_destroy])

  end

end

app/controllers/user/work_orders_controller.rb
class User::WorkOrdersController < ApplicationController
  def index
  end

  def show
  end

  def update
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[show edit update]
  # def index
  #   @work_orders = WorkOrder.all
  # end

  def index
    user = TeamLeader.find_by(user: current_user)
    @work_orders = WorkOrder.where(team_leader: user)
  end

  def new
    @work_order = WorkOrder.new
  end

  def show
    @marker = {
      lat: @work_order.latitude,
      lng: @work_order.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { work_order: @work_order })
    }
  end

  def article_params
    params.require(:article).permit(:title, :body, :photo)
  end

  def edit
  end

  def update
    @work_order.update(work_order_params)
    flash[:alert] = "Atualizado com sucesso"
    redirect_to work_orders_path(@work_order)
  end

  private

  def set_work_order
    @work_order = WorkOrder.find(params[:id])
  end

  def work_order_params
    params.require(:work_order).permit(:priority, :address, :due_time, :due_date, :description, :completion_date, :start_photo, :end_photo, :team_leader_id, :report, :status, :photo, tasks_attributes: [:id, :description, :done])
  end
end

app/views/manager/work_orders/_formedit.html.erb
<!-- <div class="container"> -->
<!--   <div class="row">
 -->
  <!-- <div class="col-6">  Início 1º Coluna  -->
                    <!-- <div class="row"> -->
                      <!-- <div class="col-4 px-3"> -->
                      <%= simple_form_for @work_order, url: manager_work_order_path do |f| %>

  <div class="row">

    <div class="col-6"> <!-- Início 1º Coluna -->

  <h1 class="p-3">Novo Job</h1>

                  <div class="card p-3">
                    <div class="row">
                      <!--  NOVO JOB -->
                      <!-- <span class="text-p col-2 px-3"> Nome:</span> -->
                      <div class="col-12 px-4">
                      <%= f.input :name, placeholder: 'Nome da WO', label: false %>
                      </div>
                    </div>

                    <div class="row p-3">
                      <div class="col-6">
                      <!-- INFOS INICIAIS -->
                      <%= f.association :team_leader, label: "Alocar a equipe:", label_method: :team_name,  include_blank: false %>
                      </div>
                      <div class="col-3">
                      <%= f.input :priority, label: "Prioridade:", collection: { Baixo: 1, Médio: 2, Alto: 3 }, include_blank: false %>
                      </div>
                      <div class="col-3">
                      <%= f.input :status, label: "Status :", collection: { Aberto: 1, "Em Andamento": 2, Concluido: 3 }, include_blank: false %>
                      </div>
                    </div>
                  </div>

  <h1 class="p-3">Localização</h1>

                    <div class="card p-3">
                      <div class="row">
                        <div class="col-4">
                          <span class="text-p">Local da operação:</span>
                        </div>
                        <div class="col-8">
                        <%= f.input :address, label: "Endereço:", placeholder: 'Inserir endereço Google Maps',label: false %>
                        </div>
                      </div>
                    </div>


  <h1 class="p-3">Datas e Horário:</h1>

                    <div class="card p-3">
                      <div class="row">
                        <div class="col-4">
                          <span class="text-p">Prazo:</span>
                        </div>
                        <div class="col-8">
                        <!-- PRAZO E HR -->
                        <%= f.input :due_date, label: "Data Prazo:", as: :date, start_year: Date.today.year, end_year: Date.today.year + 2, order: [:day, :month, :year], label: false %>
                        </div>
                      </div>


                      <div class="row">
                        <div class="col-4">
                          <span class="text-p">Horário:</span>
                        </div>
                        <div class="col-8">
                        <%= f.input :due_time, label: "Horário aproximado:", as: :time, label: false %>
                        </div>
                      </div>
                    </div>


  <h1 class="p-3">Descrição do serviço:</h1>

                    <div class="card p-3">
                      <div class="row">
                        <div class="col-4">
                          <span class="text-p">Descreva os detalhes:</span>
                        </div>
                        <div class="col-8">
                        <!-- DETALHES -->
                        <%= f.input :description, label: "Detalhes sobre o serviço:", as: :text, label: false %>
                        </div>
                      </div>
                    </div>


  </div>   <!--  Fim 1º Coluna -->

  <div class="col-6">  <!-- Início 2º Coluna -->

                      <div class="task-adding">
                        <h1>Checklist de tarefas</h1>
                        <br>


                        <div id='tasks'>
                          <span class="text-p">Descreva abaixo o <b>checklist de tarefas</b>das tarefas prioritárias para a tarefa:</span>

                          <%= f.simple_fields_for :tasks do |task| %>
                            <%= render 'task_fields', f: task %>
                          <% end %>

                          <div class='links d-flex justify-content-center align-items-center my-3'>
                            <%= link_to_add_association '', f, :tasks, class: "fas fa-plus-circle", style: "font-size: 38px; color: #7386D4;" %>
                            <span class="m-2" style="color: #A3A3A3">Adicionar tarefa</span>
                          </div>
                        </div>


                      </div>
                      <div class='block py-5'>
                      <%= f.button :submit, class: 'btn btn-primary btn-block' %>
                          <% end %>

                      <%= link_to "Excluir", manager_work_order_path(@work_order), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-secondary btn-block' %>

                      </div>

  </div> <!-- Fim 2º Coluna -->

  </div>
<!-- </div>
 --><!-- </div> -->

app/views/manager/work_orders/_info_window.html.erb
<!-- <p><%= work_order %></p>
<p><%= work_order.address %></p>
<p><%= work_order.status %></p>
<p><%= work_order.team_leader_id %></p> -->


<div class="d-flex flex-column">
  <h6> <strong><%= work_order.name %></strong> </h6>
  <div class=""> <%= work_order.address %> </div>
        <% if work_order.status == 1 %> <p class="btn btn-warning" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Aberto</p>
        <% elsif work_order.status == 2 %> <p class="btn btn-primary" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Em andamento</p>
        <% else %> <p class="btn btn-success" style="font-size: 10px; color: white; padding: 2px 15px; border-radius: 5px;">Concluido</p>
        <% end %>
  <div class=""> <%= work_order.team_leader.team_name %> </div>
</div>

app/views/manager/work_orders/_sidebar.erb
<!-- Sidebar -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>MENU</h3>
    </div>

    <ul class="list-unstyled components">
        <p>Dummy Heading</p>
        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                <a href="#">Home 1</a>
                </li>
                <li>
                <a href="#">Home 2</a>
                </li>
                <li>
                <a href="#">Home 3</a>
                </li>
            </ul>
        </li>
        <li>
        <a href="#">About</a>
        </li>
        <li class="active">
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                <a href="#">Page 1</a>
                </li>
                <li>
                <a href="#">Page 2</a>
                </li>
                <li>
                <a href="#">Page 3</a>
                </li>
            </ul>
        </li>
        <li>
        <a href="#">Portfolio</a>
        </li>
        <li>
        <a href="#">Contact</a>
        </li>
    </ul>
</nav>

app/views/manager/work_orders/_task_fields.html.erb
<div class='nested-fields'>
  <div class="card px-3 py-3 my-2">
    <div class="row ">
      <div class="col-8">
      <%= f.input :description, label: "Tarefa", placeholder: "Defina a tarefa aqui" %>
      </div>
      <div class="col-4 d-flex justify-content-around align-items-center" style="margin-top: 1rem">
        <%= f.input :done, as: :boolean, label:"Realizado" %>
        <%= link_to_remove_association "", f, class: 'fas fa-minus-circle', style: 'margin-bottom: 1rem; color: #EA5149' %>
      </div>
    </div>
  </div>
</div>

app/views/manager/work_orders/index.html.erb
<div class="conteiner">   <!-- Igual ao d-flex -->

  <div id="content">
    <button type="button" id="sidebarCollapse" class="btn btn-info">
    <i class="fas fa-align-left"></i>
    <span></span>
    </button>
    <%= render 'sidebar' %>
  </div>

  <div class="container-full content-master">
    <div class="row">
      <h4 class="title-pages">Operações | Listagem das Operações</h4>
      <div class="col-8">
            <div class="card-dashboard-header">
              <div class=" justify-content-center my-5 wo-index-page">
                <h4>Criar ordem de serviço</h4>
              <p><%= link_to "Criar Aqui", new_manager_work_order_path, class: "btn btn-primary my-2 px-5" %></p></div>
            </div>






<!-- Filtros Work Orders -->
      <div class="card m-2">
      <div class="card-header text-center" style="font-size: 12px; min-width: 309px;"></div>
      <div class="card-body text-center card-search">
              <%= form_tag manager_work_orders_path, method: :get do %>
              <div class="row">

                <span style="font-size: 12px; padding: 0px 20px;">Pesquisar :</span>

              <div class="search-form-control form-group">
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control string required",
                  placeholder: "Buscar pelo serviço" %>
                <%= submit_tag "Filtrar", class: "btn btn-outline-secondary" %>
                <% end %>
              </div>
              </div>




              <span class="card-text d-flex justify-content-center my-4" style="font-size: 10px;">
                 <form action= "work_orders" >
                    <select name="team">
                      <% @team_leaders.each do |team| %>
                        <option value="<%= team.id %>"><%= team.team_name %></option>
                      <% end %>
                    </select>
                    <select name="priority">
                      <% @work_orders_full.pluck(:priority).uniq.each do |work_order| %>
                        <option value="<%= work_order %>"><%= priority_level(work_order) %></option>
                      <% end %>
                    </select>
                    <select name="status">
                      <% @work_orders_full.pluck(:status).uniq.each do |work_order| %>
                        <option value="<%= work_order %>"><%= status_name(work_order) %></option>
                      <% end %>
                    </select>

                    <input type="submit" value="Localizar" class="btn btn-outline-secondary btn-sm m-1"><span> <%= link_to "Limpar", manager_work_orders_path, class: "btn btn-light btn-sm m-1" %></span>
                  </form>



            </span>


                  <!-- Work Orders index -->
                  <div class="card my-3 text-center" style="font-size: 11px; padding: 5px;" >
                    <table class="table table-borderless table-hover table-sm">
                                <thead class="thead-light">
                                  <tr>
                                    <th scope="col">Work Order</th>
                                    <th scope="col">Prioridade</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Team</th>
                                  </tr>
                                </thead>
                                <tbody>
                                    <% @work_orders.each do |order| %>
                                    <tr>
                                      <th scope="row"><%= link_to "#{order.name}", manager_work_order_path(order) %> </th>
                                        <td>  <% if order.priority == 3 %> <p class="btn btn-outline-danger" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Alta</p>
                                          <% elsif order.priority == 2 %> <p class="btn btn-outline-dark" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Media</p>
                                          <% else %> <p class="btn btn-outline-secondary" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Baixa</p>
                                          <% end %> </td>
                                        <td> <% if order.status == 1 %> <p class="btn btn-primary" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Aberto</p>
                                          <% elsif order.status == 2 %> <p class="btn btn-info" style="font-size: 10px; padding: 2px 15px; border-radius: 5px;">Andamento</p>
                                          <% else %> <p class="btn btn-success" style="font-size: 10px; color: white; padding: 2px 15px; border-radius: 5px;">Concluido</p>
                                          <% end %> </td>
                                        <td> <%= order.team_leader.team_name %></td>
                                    </tr>
                                    <% end %>
                                  </tbody>
                                </table>
                  </div>
          </div>
          </div>
        </div>
      <!-- Final da 2º coluna -->

</div>
</div>
</div>

app/views/manager/work_orders/show.html.erb
<div class="wrapper">
  <div id="content">
  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light"> -->
      <button type="button" id="sidebarCollapse" class="btn btn-info">
      <i class="fas fa-align-left"></i>
      <span></span>
      </button>
  <!-- </nav> -->
  <%= render 'sidebar' %>
</div>

<div class="container content-master">
  <h4 class="title-pages">Operações | Detalhes </h4>
  <div class="row justify-content-between align-items-center px-3">

    <h4>Detalhes da Operação: <br> <br> <b> <%= @work_order.name %> </b></h4>

    <div class="card px-4">
    <span class="my-2">REGISTRO: 201910-A03</span>

    <span>
      <% if @work_order.status == 1 %> <p class="btn btn-primary btn-block" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Status: &nbsp; &nbsp; &nbsp; Aberto</p>
      <% elsif @work_order.status == 2 %> <p class="btn btn-info btn-block" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Status: &nbsp; &nbsp; &nbsp; Andamento</p>
      <% else %> <p class="btn btn-success btn-block" style="font-size: 12px; color: white; padding: 2px 15px; border-radius: 5px;">Status: &nbsp; &nbsp; &nbsp; Concluido</p>
      <% end %>
    </span>

    <span>
      <% if @work_order.priority == 3 %> <p class="btn btn-outline-danger btn-block" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Prioridade: &nbsp; &nbsp; &nbsp; Alta</p>
      <% elsif @work_order.priority == 2 %> <p class="btn btn-outline-dark btn-block" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Prioridade: &nbsp; &nbsp; &nbsp; Media</p>
      <% else %> <p class="btn btn-outline-secondary btn-block" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Prioridade: &nbsp; &nbsp; &nbsp; Baixa</p>
      <% end %>
    </span>

    <span>


    </span>
    </div>
  </div>
 <!--  <div class="row d-flex justify-content-around" id="rowTopTop">
    <div class="col-6">
      <h1 class="title-pages">Operações | Visualizar Operação </h1>

    </div>
    <div class="col-4">
      <select name="due_date">
        <option ><%= @work_order.due_date %></option>
      </select>
      <br><br>
      <h1 id="h1"><%= status_name(@work_order.status) %></h1>
    </div>
  </div>
 -->

<!-- GRAFICOS  inicio -->
  <div class="row d-flex my-4">

    <div class="col-4">
      <div class="card p-3">
        <h1>Status Tarefas</h1>
        <%= pie_chart({
          "Tasks Concluídas" => @work_order.tasks.where(done: true).count,
          "Tasks em andamento" => @work_order.tasks.where(done: false).count,
          }, donut: true, colors: ["#7cc991", "#E67C73"], library: { pieSliceText: 'percentage' } )  %>
      </div>
    </div>

    <div class="col-8 d-flex justify-content-center">
      <div class="card p-3 show-card-chart" style="width: 100%;">
        <h1>Projeto - Timeline</h1>
        <%= timeline [
          ["Gerente", "2019-09-01", "2019-09-02"],
          ["Pré-visita", "2019-09-02", "2019-09-04"],
          ["Execução", "2019-09-04", "2019-09-10"],
          ["Fase-01", "2019-09-06", "2019-09-08"],
          ["Fase-02", "2019-09-08", "2019-09-10"],
          ["Fase-03", "2019-09-10", "2019-09-12"]
        ] %>
      </div>
    </div>

  </div>
<!-- GRAFICOS  fim -->


  <div class="row d-flex align-items-center my-5" id="rowBottom">


    <div class="col-8"> <!-- 1º Coluna inicio -->


      <h1> <b>Detalhes da Operação:</b></h1>

      <div class="row">
        <div class="card justify-content-center" id="a">
          <h1>Ordem de serviço:</h1> <div class="card p-3" id="x"><%= @work_order.name %></div>
          <p><h1>Equipe:</h1>
            <div class="card p-3" id="x"><%= @work_order.team_leader.team_name %></div>
          <p><h1>Operador:</h1><div class="card p-3" id="x"> <%= @work_order.team_leader.user.name %> </div>
          <p><h1>Prazo:</h1><div class="card p-3" id="x"> <%= @work_order.due_date %> </div>
          </%>
          <p><h1>Prioridade:</h1> <div class="card p-3" id="x"> <%= priority_level(@work_order.priority) %> </div>
        </div>
      </div>
      <div class="row">
        <div class="card justify-content-center" id="b">
          <h1>Status operacional:</h1>

        <span>
          <% if @work_order.status == 1 %> <p class="btn btn-primary btn-lg" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Aberto</p>
          <% elsif @work_order.status == 2 %> <p class="btn btn-info btn-lg" style="font-size: 12px; padding: 2px 15px; border-radius: 5px;">Andamento</p>
          <% else %> <p class="btn btn-success btn-lg" style="font-size: 12px; color: white; padding: 2px 15px; border-radius: 5px;">Concluido</p>
          <% end %>
        </span>


        </div>
      </div>
      <div class="row">
        <div class="card justify-content-center" id="c">
          <p><h1>Descrição:</h1> <%= @work_order.description %></p>
        </div>
      </div>

      <div class="row">
        <div class="card card-task-show" id="d">
          <h1>Report operacional:</h1>
          <span class="card p-4 my-3 card-report">
          <%= @work_order.report %>
          </span>
            <!-- TASKS -->
            <%= simple_form_for @work_order do |f| %>
              <h1>Tasks</h1>
              <div id='tasks'>
                <%= f.simple_fields_for :tasks do |task| %>
                <%#= render 'task_fields', :f => task %>
                  <div class='nested-fields'>
                    <div class="card px-3 py-3 my-2">
                      <div class="row ">
                        <div class="col-8">
                          <%= task.object.description %>
                        </div>
                        <div class="col-4 d-flex justify-content-around align-items-center" style="margin-top: 1rem">

                          <% if task.object.done %>
                           <span class="badge badge-pill badge-success">Realizado</span>
                          <% else %>
                            <span class="badge badge-pill badge-danger">Aberto</span>
                          <% end %>

                        </div>
                      </div>
                    </div>
                  </div>
              <% end %>
            <% end %>
          </div> <!-- END TASKS -->
        </div>
      </div>


    </div> <!-- 1º Coluna fim -->



    <div class="col-4"> <!--2º Coluna início -->

        <!-- BOX STATUS TASKs -->
        <div>
        <h1>Tarefas</h1>
        <div class="row justify-content-end">
        <div class="card text-white bg-success m-1" style="width: 120px;">
          <div class="card-header text-center" style="font-size: 13px;">Concluídos</div>
          <div class="card-body">
            <h5 class="card-title text-center" style="font-size: 28px;"><%= @work_order.tasks.where(done: true).count %></h5>
          </div>
        </div>
        <div class="card text-white bg-danger m-1" style="width: 120px;">
          <div class="card-header text-center" style="font-size: 13px;">Não Realizado</div>
          <div class="card-body">
            <h5 class="card-title text-center" style="font-size: 28px;"><%= @work_order.tasks.where(done: false).count %></h5>
          </div>
        </div>
        </div>
        </div>



      <div class="photo my-5">
        <h1>Documentação</h1>
        <%= cl_image_tag @work_order.start_photo, height: 180, width: 370, crop: :fill %>
        <br><br>
        <%= cl_image_tag @work_order.end_photo, height: 180, width: 370, crop: :fill %>
      </div>


      <h1>Endereço:</h1> <p><%= @work_order.address %></p>

      <div
      id="map"
      style="width: 370px;
      height: 280px;"
      data-markers="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

      <div class="row justify-content-center m-5" >
      <%= link_to "Editar", edit_manager_work_order_path(@work_order), class:"btn btn-outline-secondary btn-block" %>
      </div>
    </div> <!-- 2º Coluna fim  -->

  </div>
</div>