config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # USER
  resources :work_orders, only: [:index, :show, :edit, :update]

  # ADMIN
  # namespace
  # after_create in user to create manager
  namespace :manager do
    resources :work_orders
    resources :team_leaders
    resources :dashboard, only: :index
  end

end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
  # enum status: { Aberta: 0, 'Em andamento': 1, Concluido: 2 }
  has_many :tasks, inverse_of: :work_order, dependent: :destroy
  belongs_to :team_leader

  accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: true

  geocoded_by :address
  validates :name, uniqueness: true
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :start_photo, PhotoUploader
  mount_uploader :end_photo, PhotoUploader
end

app/controllers/manager/work_orders_controller.rb
class Manager::WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[show edit update destroy]

  def index
    @team_leaders = TeamLeader.all
    @work_orders_full = WorkOrder.all
    @work_orders = @work_orders_full

    @work_orders = WorkOrder.where("name ILIKE ?", "%#{params[:query]}%") if params[:query].present?
    @work_orders = @work_orders.where(team_leader_id: params[:team]) if params[:team].present?
    @work_orders = @work_orders.where(priority: params[:priority]) if params[:priority].present?
    @work_orders = @work_orders.where(status: params[:status]) if params[:status].present?
    @work_orders = @work_orders.where(due_date: params[:due_date]) if params[:due_date].present?

    @events = WorkOrder.where.not(due_date: nil).map { |w| { title: w.name, start: w.due_date } }
  end

  def new
    @work_order = WorkOrder.new
  end

  def show
    @marker = {
      lat: @work_order.latitude,
      lng: @work_order.longitude,
      image_url: helpers.asset_url('shovel_marcador.png'),
      infoWindow: render_to_string(partial: "info_window", locals: { work_order: @work_order })
    }


    # @work_order.tasks.pluck(:done)
    # @chart = WorkOrder.group(:done).count
    # @chart.keys.each do |key|
    #   @chart[['Aberto', 'Em andamento', 'Concluído'][key - 1]] = @chart.delete key
    # end
  end

  def create
    @work_order = WorkOrder.new(work_order_params)
    # raise
    if @work_order.save
      redirect_to manager_dashboard_index_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @work_order.update(work_order_params)
    redirect_to manager_work_orders_path
  end

  def destroy
    @work_order.destroy
    redirect_to manager_dashboard_index_path
  end

  private

  def set_work_order
    @work_order = WorkOrder.find(params[:id])
  end

  def work_order_params
    params.require(:work_order).permit( :name,
                                        :priority,
                                        :address,
                                        :due_time,
                                        :due_date,
                                        :description,
                                        :completion_date,
                                        :start_photo,
                                        :end_photo,
                                        :team_leader_id,
                                        :status,
                                        :report,
                                        tasks_attributes: [:id, :description, :done, :_destroy])

  end

end

app/controllers/user/work_orders_controller.rb
class User::WorkOrdersController < ApplicationController
  def index
  end

  def show
  end

  def update
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: %i[show edit update]
  # def index
  #   @work_orders = WorkOrder.all
  # end

  def index
    user = TeamLeader.find_by(user: current_user)
    @work_orders = WorkOrder.where(team_leader: user)
  end

  def new
    @work_order = WorkOrder.new
  end

  def show
    @marker = {
      lat: @work_order.latitude,
      lng: @work_order.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { work_order: @work_order })
    }
  end

  def article_params
    params.require(:article).permit(:title, :body, :photo)
  end

  def edit
  end

  def update
    @work_order.update(work_order_params)
    flash[:alert] = "Atualizado com sucesso"
    redirect_to work_orders_path(@work_order)
  end

  private

  def set_work_order
    @work_order = WorkOrder.find(params[:id])
  end

  def work_order_params
    params.require(:work_order).permit(:priority, :address, :due_time, :due_date, :description, :completion_date, :start_photo, :end_photo, :team_leader_id, :report, :status, :photo, tasks_attributes: [:id, :description, :done])
  end
end

app/views/work_orders/_info_window.html.erb
<p><%= work_order.name %></p>
<p><%= work_order.address %></p>
<p><%= work_order.status %></p>
<p><%= work_order.team_leader_id %></p>

app/views/work_orders/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-mobile ">
  <%= link_to "#", class: "navbar-brand" do %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars" style="font-size: 36px; color: white"></i>
    <!-- <span class="navbar-toggler-icon"></span> -->
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="row d-flex userbtn-index">
  <div class="col-12">
    <h6 style="padding: 7px;background-color: #FFBA00; width:150px; border-radius: 2px;color:white; margin-top: 4px; text-align: center;"><%= current_user.name %></h6>
  </div>
</div>

<div class="container my-5">
  <div class="single-item text-center " >
    <% @work_orders.each do |work_order| %>
      <div class="card p-5 rounded-sm form-postt usercard" style="width: 80%;">
        <i class="fab fa-get-pocket" style="font-size: 60px;"></i>
       <!--  <img src="https://images.unsplash.com/photo-1551711975-585d41fad0c2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80" class="card-img-top" alt="..."> -->
        <div class="card-body my-2">
            <h4><%= work_order.name.upcase %></h4>
          <br>


          <% if work_order.priority == 3 %> <p class="btn-danger userbtn-index" style="font-size: 14px; padding: 2px 15px; border-radius: 5px;">Alta</p>
            <% elsif work_order.priority == 2 %> <p class="btn-warning userbtn-index" style="font-size: 14px; padding: 2px 15px; border-radius: 5px;">Media</p>
            <% else %> <p class="btn-primary userbtn-index" style="font-size: 14px; padding: 2px 15px; border-radius: 5px;">Baixa</p>
          <% end %>

          <% if work_order.status == 1 %> <p class="btn-warning userbtn-index" style="font-size: 14px; padding: 2px 15px; border-radius: 5px;">Aberto</p>
            <% elsif work_order.status == 2 %> <p class="btn-primary userbtn-index" style="font-size: 14px; padding: 2px 15px; border-radius: 5px;">Em andamento</p>
            <% else %> <p class="btn-primary userbtn-index" style="font-size: 14px; padding: 2px 15px; border-radius: 5px;">Concluido</p>
          <% end %>



          <p class="card-text">Gestão de WO's nunca foi tão eficiente.</p>
          <br>
          <br>
           <%= link_to "Acessar", work_order_path(work_order), :class => "btn btn-block btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/work_orders/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-mobile ">
  <%= link_to "#", class: "navbar-brand" do %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
    <!-- <span class="navbar-toggler-icon"></span> -->
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
      <li class="nav-item dropdown">

        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="container p-3 mb-3 bg-white rounded">
  <div class="card py-5 px-4 mb-2 bg-white rounded shadow-sm">
  <h3 align="center"> Ordem de Serviço</h3>

      <h4 align="center"><%= @work_order.name %></h4>

          <% if @work_order.priority == 3 %> <p class="btn-danger userbtn btn-lg" style="font-size: 15px; padding: 2px 15px; border-radius: 5px;">Prioridade:  Alta</p>
            <% elsif @work_order.priority == 2 %> <p class="btn-warning userbtn btn-lg" style="font-size: 15px; padding: 2px 15px; border-radius: 5px;">Prioridade:  Media</p>
            <% else %> <p class="btn btn-primary btn-lg" style="font-size: 15px; padding: 2px 15px; border-radius: 5px;">Prioridade:  Baixa</p>
          <% end %>

          <% if @work_order.status == 1 %> <p class="btn-warning userbtn" style="font-size: 15px; padding: 2px 15px; border-radius: 5px;">Status: Aberto</p>
            <% elsif @work_order.status == 2 %> <p class="btn-primary userbtn" style="font-size: 15px; padding: 2px 15px; border-radius: 5px;">Status: Em andamento</p>
            <% else %> <p class="btn btn-success" style="font-size: 15px; color: white; padding: 2px 15px; border-radius: 5px;">Status: Concluido</p>
          <% end %>

      <p class="card" align="center" style= "font-size: 0.9em; padding: 15px 8px;"><%= @work_order.description %></p>
</div>

<div class="container card p-3 mb-2 bg-white rounded shadow-sm">
  <h6 align="center"><%= @work_order.address%> </h6>

  <div
    id="map"
    style="width: 100%;
    height: 300px;"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

<div class="container shadow-lg p-3 mb-3 bg-white rounded">

  <div class="">

    <%= simple_form_for @work_order do |f| %>


    <div id='tasks'>
    <h4>Tarefas:</h4>
    <%= f.simple_fields_for :tasks do |task| %>
    <div class='nested-fields'>
      <div class="card m-2">
      <div class="row m-2">
        <div class="col-8">
          <div class="pl-2 pr-4 py-2">
            <%= task.object.description %>
          </div>
        </div>
        <div class="col-4">
            <%= task.input :done, :as => :boolean %>
        </div>
      </div>
      </div>
    </div>

    <% end %>


    <%= f.input :report %>
    <%= f.input :status, collection: { Aberto: 1, "Em Andamento": 2, Concluido: 3 } %>
    <%= f.input :start_photo, input_html: { class: 'hidden' }, label_html: { class: 'upload-photo'}, label: ' 📷 Upload Start Photo', class: "btn-primary" %>
    <%= f.input :end_photo, input_html: { class: 'hidden' }, label_html: { class: 'upload-photo'}, label: ' 📷 Upload End Photo', class: "btn-primary" %>

    <div class="m-5">
    <div class="row justify-content-center">
    <%= f.button :submit, class: "btn btn-primary" %>
    <%= f.input :start_photo_cache, as: :hidden %>
    <%= f.input :end_photo_cache, as: :hidden %>
    <% end %>
    </div>
    </div>

   </div>
</div>